export default {
  订单编号: 'tdNo',
  类别: 'category',
  运单状态: 'state',
  转运状态: 'transferState',
  付款方式: 'paymentType',
  取件人确认信息: 'pickerAllowState',
  运单来源: 'sourceType',
  派件方式: 'sendMethod',
  支付状态: 'paymentState',
  签收状态: 'signState',
  开票状态: 'receiptState',
  寄件人姓名: 'sender',
  寄件人电话: 'senderPhone',
  寄件地址: 'sendAddress',
  开票状态: 'receiptState',
  收件人姓名: 'receiver',
  收件人电话: 'receiverPhone',
  收件地址: 'receiverAddress',
  计费重量: 'goodsWeight',
  货物信息: 'goodsInfo',
  期望班车时间: 'expectBusTime',
  实际班车时间: 'busTime',
  客户备注: 'remark',
  下单时间: 'createTime',
  寄件日期: 'sendDate',
  取件人: 'picker',
  取件时间: 'pickTime',
  派件人: 'deliver',
  派件时间: 'deliveryTime',
  派件派件员到达派件点时间: 'arrivalDeliveryTime',
  签收人: 'signer',
  签收时间: 'signTime',
  寄件网点: 'sendSite',
  目的网点: 'receiveSite',
  寄件网点出库日期: 'departTime',
  目的地网点入库时间: 'arriveTime',
  标准运费: 'normal',
  保价费: 'insurance',
  其他运费: 'other',
  总费用: 'total',
  上一个状态: 'lastState',
  操作网点: 'operationSite',
  操作人: 'operator',
  问题类型: 'problemType',
  问题件描述: 'problemDetail',
  取消类型: 'cancelType',
  取消类别: 'cancelCategory',
  退回件类型: 'refundType',
  退回件描述: 'refundDetail',
  退回件描述: 'operateTime',
  寄件人: 'sender',
  收件人: 'receiver',
  收件人地址: 'receiverAddress',
  寄件人地址: 'senderAddress',
  收寄件人姓名: 'name',
  收寄件人电话:'tel',
  收寄件人地址:'address',
  收寄件人证件号:'cardCode',
  收寄件人证件类型:'cardType',
  收寄件人邮编:'postcode',
  收寄件人国家地区:'city',
  备注:'remark',
  类型:'type',

}
